=== 2020cguo/O28r/pmd-test-schema/src/main/resources/net/sourceforge/pmd/test.schema/rule-tests_1_0_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
    xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://pmd.sourceforge.net/rule-tests"
    xmlns:tns="http://pmd.sourceforge.net/rule-tests"
    elementFormDefault="qualified">

    <element name="test-data">
        <complexType>
            <group ref="tns:testCodeOrCodeFragment" minOccurs="1" maxOccurs="unbounded"/>
        </complexType>
    </element>

    <group name="testCodeOrCodeFragment">
        <sequence>
            <element name="test-code" minOccurs="0" maxOccurs="unbounded" type="tns:testCodeType"/>
            <element name="code-fragment" minOccurs="0" maxOccurs="unbounded" type="tns:codeFragmentType"/>
        </sequence>
    </group>

    <complexType name="testCodeType">
        <sequence>
            <element name="description" type="string"/>
            <element name="rule-property" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <simpleContent>
                        <extension base="string">
                            <attribute name="name" type="string" use="required"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>
            <element name="expected-problems" type="integer"/>
            <element name="expected-linenumbers" type="string" minOccurs="0"/>
            <element name="expected-messages" minOccurs="0">
                <complexType>
                    <sequence>
                        <element name="message" type="string" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
            <choice>
                <element name="code"/>
                <element name="code-ref">
                    <complexType>
                        <attribute name="id" type="IDREF" use="required"/>
                    </complexType>
                </element>
            </choice>
            <element name="source-type" minOccurs="0" default="java" type="string"/>
        </sequence>
        <attribute name="reinitializeRule" type="boolean" default="true"/>
        <attribute name="regressionTest" type="boolean" default="true"/>
        <attribute name="useAuxClasspath" type="boolean" default="true"/>
    </complexType>

    <complexType name="codeFragmentType">
        <simpleContent>
            <extension base="string">
                <attribute name="id" type="ID" use="required"/>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== 2020cguo/O28r/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AvoidArrayLoops.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>copy index into array</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        for (int i=0;i<10;i++) {
            a[i] = i;
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>copy one array to another</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        for (int i=0;i<10;i++) {
            a[i] = b[i];
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>copy via while loop</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        int i = 0;
        while (i < 10) {
            a[i] = b[i];
            i++;
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>copy involving multiple arrays is ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        for (int i = 0; i < 10; i++) {
            x[i] = b[i] + 1;
            y[i] = a[i] + 2;
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>copy involving method invocation on array element is ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        for (int i=0;i<10;i++) {
            a[i] = b[i].size();
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>using an offset, still bad</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        for (int i=0;i<10;i++) {
            b[i]=a[i+6];
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>nested arrays on LHS, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        for (int i=0;i<10;i++) {
            b[c[i]] = a[i];
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>adding to array is ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar1() {
        for (int i = 0; i < 10; i++) {
            a[i] += b[i];
        }
    }
    public void bar2() {
        int i = 0;
        for (i = 0; i < 10; i++) {
            a[i] += b[i];
        }
    }
}
        ]]></code>
    </test-code>
    
    <test-code>
        <description>[java] AvoidArrayLoops false positive on double assignment #1167</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Test {
  public static void main( String[] args ) {
    double[] foo = new double[100];
    double bar = 0.0;
    int[] exps = new int[10];

    for (int i = 0; i < exps.length; i++) {
      double value = Math.random();
      foo[i] = Math.exp(value);
      bar += foo[i];
    }
  }
}
]]></code>
    </test-code>

    <test-code>
        <description>Nested array on RHS</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
class AvoidArrayLoops {
  void copy_a_to_b(int[] a, int[] b) {
        int[] c = new int[10];
        // this will not trigger the rule
        for (int i = 0; i < 10; i++) {
            b[i] = a[c[i]];
        }
  }
}
]]></code>
    </test-code>
</test-data>

=== 2020cguo/O28r/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/EmptyControlStatement.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data xmlns="http://pmd.sourceforge.net/rule-tests"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>pos, empty try block</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
            public class EmptyTryBlock1 {
                public void foo() {
                    try {
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>pos, empty try block</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
            public class EmptyTryBlock2 {
                public void foo() {
                    try {
                    } finally {
                        int x = 5;
                    }
                }
            }
            ]]></code>
    </test-code>
    <test-code>
        <description>pos, empty finally block</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>5</expected-linenumbers>
        <code><![CDATA[
            public class EmptyTryBlock2 {
                public void foo() {
                    try {
                        int x = 0;
                    } finally { // warn
                    }
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>pos, empty finally block</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public class EmptyTryBlock3 {
                public void foo() {
                    try {
                        int f =2;
                    } finally {
                        int x = 5;
                    }
                }
            }
            ]]></code>
    </test-code>
    <test-code>
        <description>pos, empty try and finally block</description>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
            public class EmptyTryBlock3 {
                public void foo() {
                    try {
                    } finally {
                    }
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>#432 empty try-with-resource - not ok</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
            class X {
                void method() {
                    try (ClientResponse response = execute(() -> target.request(mediaTypes).delete(), DELETE, new ExpectedResponse(status, required))) {
                        // false positive
                    }
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>#432 empty try-with-resource - ok with unused var name</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            class X {
                void method() {
                    try (ClientResponse ignored = execute(() -> target.request(mediaTypes).delete(), DELETE, new ExpectedResponse(status, required))) {
                    }
                }
            }
            ]]></code>
    </test-code>


    <test-code>
        <description>pos, empty synchronized stmt</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
            public class Foo {
                void foo() {
                    synchronized (this) {}
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>neg, nonempty synchronized stmt</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public class Foo {
                void foo() {
                    synchronized (this) {int x = 2;}
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>pos, empty switch stmt</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
            public class EmptySwitchStmt1 {
                public void bar() {
                    int x = 2;
                    switch (x) {}
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>neg, nonempty switch stmt</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public class EmptySwitchStmt2 {
                public void bar() {
                    int x = 2;
                    switch (x) {
                    case 2: int y=4;
                    }
                }
            }
            ]]></code>
    </test-code>


    <test-code>
        <description>pos, empty block</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
            public class Foo {
                public void bar() {
                    {}
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>statement block not empty</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public class Foo {
                public void bar() {
                    { return; }
                }
            }
            ]]></code>
    </test-code>
    
    <test-code>
        <description>failure case (non static)</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
            public class Foo {
                {}
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>failure case (static)</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
            public class Foo {
                static {}
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>not an initializer</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
            public class Foo {
                public void bar() {
                    { }
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>initializer not empty</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public class Foo {
                {
                    System.out.print("something interesting");
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>static initializer not empty</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public class Foo {
                static {
                    x++;
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>pos, empty while</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
            public class Foo {
                public void bar() {
                    while (true == true) {
                    }
                    while (true == true) {
                        String x = "";
                    }
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>while(true);</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
            public class Foo {
                public void bar() {
                    while (true);
                }
            }
            ]]></code>
    </test-code>
</test-data>

=== 2020cguo/O28r/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/NonSerializableClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Example code</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>6</expected-linenumbers>
        <expected-messages>
            <message>The field 'stream' of serializable class 'Buzz' is of non-serializable type 'java.io.InputStream'.</message>
        </expected-messages>
        <code><![CDATA[
class Buzz implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private transient int someFoo;      // good, it's transient
    private static int otherFoo;        // also OK, it's static
    private java.io.InputStream stream; // bad - InputStream is not serializable

    public void setStream(InputStream stream) {
        this.stream = stream;
    }

    public int getSomeFoo() {
          return this.someFoo;
    }
}
]]></code>
    </test-code>

    <test-code>
        <description>String, no accessor, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.io.Serializable;
public class Foo implements Serializable {
    private String foo;
    private String bar = foo;
}
        ]]></code>
    </test-code>

    <test-code>
        <description>private static InputStream</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.io.InputStream;
import java.io.Serializable;
public class Foo implements Serializable {
    private static InputStream foo;
}
        ]]></code>
    </test-code>

    <test-code>
        <description>private transient InputStream</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.io.InputStream;
import java.io.Serializable;
public class Foo implements Serializable {
    private transient InputStream foo;
}
        ]]></code>
    </test-code>

    <test-code>
        <description>InputStream in a non-serializable class is OK</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.io.InputStream;
public class Foo {
    private InputStream foo;
}
]]></code>
    </test-code>

    <test-code>
        <description>interface</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.io.InputStream;
import java.io.Serializable;
public interface Foo extends Serializable {
    public InputStream getFoo();
}
        ]]></code>
    </test-code>

    <test-code>
        <description>@SuppressWarnings("serial")</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.io.InputStream;
import java.io.Serializable;
@SuppressWarnings("serial")
public class Foo implements Serializable {
    private InputStream foo;
}
        ]]></code>
    </test-code>

    <test-code>
        <description>ClassCastException on generic method</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.util.List;
public abstract class List<A> implements Iterable<A> {
    public static <A> F<List<A>, Boolean> isEmpty() {
        return null;
    }
}
class F<X, Y> {}
        ]]></code>
    </test-code>

    <test-code>
        <description>Ignore Externalizable</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.io.Externalizable;
import java.io.InputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectInput;
class Foo implements Externalizable {
    private InputStream foo;
    void writeExternal(ObjectOutput out) throws IOException {}
    void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {}
}
]]></code>
    </test-code>

    <test-code>
        <description>Ignore manual serialization</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.io.InputStream;
import java.io.Serializable;
import java.io.IOException;
import java.io.ObjectStreamException;
class Foo implements Serializable {
    private InputStream foo; // no violation, because writeObject/readObject is present
    private void writeObject(java.io.ObjectOutputStream out) throws IOException {}
    private void readObject(java.io.ObjectInputStream in) throws IOException, ClassNotFoundException {}
    private void readObjectNoData() throws ObjectStreamException {}
}
]]></code>
    </test-code>

    <test-code>
        <description>Ignore manual serialization with replacement object</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.io.InputStream;
import java.io.Serializable;
import java.io.ObjectStreamException;
class Foo implements Serializable {
    private InputStream foo; // no violation, because writeReplace/readResolve is present
    private Object writeReplace() throws ObjectStreamException {}
    private Object readResolve() throws ObjectStreamException {}
}
]]></code>
    </test-code>
</test-data>

=== 2020cguo/O28r/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/AddEmptyString.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">
    <test-code>
	    <description>Test case in issue 3625</description>
	    <expected-problems>1</expected-problems>
	    <code><![CDATA[
public class Main {
	public void func() {
		final String var = "";
		String test = var + "123"; // should report a warning here
	}
}

	    ]]></code>
    </test-code>
    <test-code>
	    <description>Local Variables be empty String</description>
	    <expected-problems>3</expected-problems>
	    <code><![CDATA[
public class Main
{
	public static void main(String[] args)
	{
		String string1 = "";
		String string2 = "";
		String string3 = "";

		String a = string1 + 114;
		String b = string2 + 514;
		String c = string3 + 1919810;
	}
}
	    ]]></code>
    </test-code>
    <test-code>
	    <description>Local and global variables be empty String</description>
	    <expected-problems>4</expected-problems>
	    <code><![CDATA[
public class Main
{
	final String outerString1 = "";
	final String outerString2 = "";

	public static void main(String[] args)
	{
		final String innerString1 = "";
		final String innerString2 = "";

		String a = outerString1 + 114;
		String b = outerString2 + 514;
		String c = innerString1 + 1919;
		String d = innerString2 + 810;
	}
}
	    ]]></code>
    </test-code>
    <test-code>
	    <description>Test case in issue 3625</description>
	    <expected-problems>1</expected-problems>
	    <code><![CDATA[
public class Main {
	public void func() {
		final String var = "";
		String test = var + "123"; // should report a warning here
	}
}

	    ]]></code>
    </test-code>
    <test-code>
        <description>Bad add</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        String s = "" + 123;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Good add</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        String s = "1" + 123;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Good convert</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        String t = Integer.toString(456);
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Ignore in annotations</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    private static final int VERSION = 1;

    @Deprecated(since = "" + VERSION)
    public void foo() {
    }
}
        ]]></code>
    </test-code>
</test-data>

=== 2020cguo/O28r/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/InvalidJavaBean.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
        xmlns="http://pmd.sourceforge.net/rule-tests"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Example code</description>
        <expected-problems>2</expected-problems>
        <expected-linenumbers>1,2</expected-linenumbers>
        <expected-messages>
            <message>The bean 'MyBean' does not implement java.io.Serializable.</message>
            <message>The bean 'MyBean' is missing a setter for property 'label'.</message>
        </expected-messages>
        <code><![CDATA[
public class MyBean {        // <-- bean is not serializable, missing "implements Serializable"
    private String label;    // <-- missing setter for property "label"

    public String getLabel() {
        return label;
    }
}
        ]]></code>
    </test-code>
</test-data>
